<?php 
    /* 
    revisão:
    SUPERGLOBAIS
        $_POST -> RECEBE E MANIPULA INFORMAÇÕES ENVIADAS DO FORMULARIO VIA METODO POST
        $_GET -> RECEBE E MANIPULA INFORMAÇÕES ENVIADAS DO FORMULARIO VIA METODO GET
        $_REQUESTE -> RECEBE E MANIPULA INFORMAÇÕES ENVIADAS DO FORMULARIO
        $_FILE -> RECEBE E MANIPULA INFORMAÇÕES BINÁRIAS DE FORMULARIO
        $_COOKIE -> MANIPULA COOKIE NO BROWSER
        $_SESSION -> MANIPULA SESSÃO NO SERVIDOR 
 */

 // $variavel = (condição) ? if : else
 
?>  